# This docker-compose script builds our program from scratch, and also
# runs the requisite postgres image.
version: "3.5"

services:
  fibsrv:
    build: .
    ports:
      - '8080:8080'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: fib_db
    depends_on: [db]

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: fib_db